spring.application.name=root
server.port=8080

#database property
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-ems-assignment
spring.datasource.username=postgres
spring.datasource.password=0009

# Hibernate / JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialect (important for PostgreSQL)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
